{
 "title": "Payments",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Времени без блокировки счета",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "maryno_net_days_since_block" }
   ]
  },
  {
   "title": "Состояние счета",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "maryno_net_is_blocked" }
   ]
  },
  {
   "title": "Последняя оплата",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "maryno_net_last_pay_seconds * 1000"
    }
   ]
  },
  {
   "title": "Сумма последней оплаты",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "maryno_net_last_pay_sum" }
   ]
  },
  {
   "title": "Потрачено на интернет",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "maryno_net_sum_pays" }
   ]
  },
  {
   "title": "Баланс счета Maryno.net",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "yaxes": [
    { "format": "currencyRUB" }
   ],
   "targets": [
    { "expr": "maryno_net_balance", "legendFormat": "Баланс счета" },
    { "expr": "maryno_net_plan_cost", "legendFormat": "Стоимость в месяц" }
   ]
  },
  {
   "title": "G-Bonus",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "maryno_net_bonus_count", "legendFormat": "Общее количество бонусов" },
    { "expr": "maryno_net_bonus_available", "legendFormat": "Доступные бонусы" }
   ]
  },
  {
   "title": "До нового уровня G-Bonus",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "yaxes": [
    { "format": "currencyRUB" }
   ],
   "targets": [
    { "expr": "maryno_net_sum_pays", "legendFormat": "Всего оплачено" },
    { "expr": "maryno_net_sum_pays_remaining", "legendFormat": "Осталось до уровня" }
   ]
  }
 ]
}